#page title
page_title                                : Ilim App                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1568913668                               # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : au                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://apps.apple.com/au/app/ilim-college/id1568913668?platform=iphone # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                        # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Ilim College App                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : By Bashir Rahmah                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Student Initiative School App

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Bashir Rahmah                                
your_link                                 :       
your_city                                 : Melbourne                                
email_address                             : brahmah90@gmail.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : Brahmah
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Plan Your Day At A Glance
    description                           : View your calendar integrating numerous college services.
    fontawesome_icon_name                 : magic
    
  - title                                 : Keep Up-To-Date
    description                           : Explore all college news (even schoolbox!), events and activities in your inbox feed.
    fontawesome_icon_name                 : mobile

  - title                                 : Collaborate
    description                           : Communicate with your classmates and teachers through the social stream integration in the inbox.
    fontawesome_icon_name                 : play-circle

  - title                                 : Easy to Tweak
    description                           : Tweak your inbox feed to show only what you want.
    fontawesome_icon_name                 : adjust

  - title                                 : Assessments
    description                           : Scan your work, Type it in the app, or upload it and view your teachers feedback.
    fontawesome_icon_name                 : book
  
  - title                                 : Attendance
    description                           : Insights into your attendance summary with detailed daily and semesterly breakdowns. Attendance is even integrated into the timetable!
    fontawesome_icon_name                 : star

  - title                                 : Pages
    description                           : Naitively interact with schoolbox class, unit, and even course pages.
    fontawesome_icon_name                 : link

  - title                                 : Class Resources
    description                           : Easily view, annotate, and download resources right in the app. 
    fontawesome_icon_name                 : arrow-alt-circle-down

  - title                                 : Widgets
    description                           : Explore your timetable and inbox from your home screen.
    fontawesome_icon_name                 : info-circle
    
  - title                                 : Push Notifications
    description                           : Recieve realtime schoolbox push notifications to stay up-to-date.
    fontawesome_icon_name                 : info-circle




# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : blue                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
